# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  push:
      branches:
        - main

env:
  AZURE_WEBAPP_NAME: "https://lanallai-load-test.azurewebsites.net"    # set this to your application's name
  LOAD_TEST_RESOURCE: "lanallai-load-tester"
  LOAD_TEST_RESOURCE_GROUP: "lanallai-load-testeastus-rg"
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.15.1'                # set this to the node version to use
  LOCATION: "East US"
  APPINSIGHTLOCATION: "East US"
  DATABASEACCOUNTLOCATION: "eastus"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  loadTest:
    name: Load Test   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/powershell@v1
        continue-on-error: false
        with:
          inlineScript: |
            az group create --name "${{ env.LOAD_TEST_RESOURCE_GROUP }}" --location "${{ env.LOCATION }}"
          azPSVersion: "latest"      
          
      - name: Create Azure Load Testing resource
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          template: ./ARMTemplate/template.json
          parameters: ./ARMTemplate/parameters.json name=${{ env.LOAD_TEST_RESOURCE }} location="${{ env.LOCATION }}"
          
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'SampleApp.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]          
      
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
